name: reactive_notify
description: A Dart library for managing reactive state efficiently, supporting multiple independent instances with unique keys.

version: 2.1.2
homepage: https://github.com/JhonaCodes/reactive_notify.git

environment:
  sdk: '>=3.4.3 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0
  alchemist: ^0.7.0
